/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PortfolioIndexImport } from './routes/portfolio/index'
import { Route as MyWalletIndexImport } from './routes/my-wallet/index'
import { Route as FundsIndexImport } from './routes/funds/index'
import { Route as FundOperateIndexImport } from './routes/fund-operate/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioIndexRoute = PortfolioIndexImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any)

const MyWalletIndexRoute = MyWalletIndexImport.update({
  id: '/my-wallet/',
  path: '/my-wallet/',
  getParentRoute: () => rootRoute,
} as any)

const FundsIndexRoute = FundsIndexImport.update({
  id: '/funds/',
  path: '/funds/',
  getParentRoute: () => rootRoute,
} as any)

const FundOperateIndexRoute = FundOperateIndexImport.update({
  id: '/fund-operate/',
  path: '/fund-operate/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fund-operate/': {
      id: '/fund-operate/'
      path: '/fund-operate'
      fullPath: '/fund-operate'
      preLoaderRoute: typeof FundOperateIndexImport
      parentRoute: typeof rootRoute
    }
    '/funds/': {
      id: '/funds/'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsIndexImport
      parentRoute: typeof rootRoute
    }
    '/my-wallet/': {
      id: '/my-wallet/'
      path: '/my-wallet'
      fullPath: '/my-wallet'
      preLoaderRoute: typeof MyWalletIndexImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fund-operate': typeof FundOperateIndexRoute
  '/funds': typeof FundsIndexRoute
  '/my-wallet': typeof MyWalletIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fund-operate': typeof FundOperateIndexRoute
  '/funds': typeof FundsIndexRoute
  '/my-wallet': typeof MyWalletIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fund-operate/': typeof FundOperateIndexRoute
  '/funds/': typeof FundsIndexRoute
  '/my-wallet/': typeof MyWalletIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fund-operate' | '/funds' | '/my-wallet' | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fund-operate' | '/funds' | '/my-wallet' | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/fund-operate/'
    | '/funds/'
    | '/my-wallet/'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundOperateIndexRoute: typeof FundOperateIndexRoute
  FundsIndexRoute: typeof FundsIndexRoute
  MyWalletIndexRoute: typeof MyWalletIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundOperateIndexRoute: FundOperateIndexRoute,
  FundsIndexRoute: FundsIndexRoute,
  MyWalletIndexRoute: MyWalletIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fund-operate/",
        "/funds/",
        "/my-wallet/",
        "/portfolio/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fund-operate/": {
      "filePath": "fund-operate/index.tsx"
    },
    "/funds/": {
      "filePath": "funds/index.tsx"
    },
    "/my-wallet/": {
      "filePath": "my-wallet/index.tsx"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
