export const POLL_BALANCES_MY_WALLET_INTERVAL = 0;
export const POLL_BALANCES_PORTFOLIO_INTERVAL = 1000 * 30;
export const POLL_BALANCES_FUND_OPERATE_INTERVAL = 1000 * 30;

export const POLL_VAULTS_DATA_FUNDS_INTERVAL = 1000 * 60 * 5;
export const POLL_VAULTS_DATA_PORTFOLIO_INTERVAL = 1000 * 60 * 5;
export const POLL_VAULTS_DATA_FUND_OPERATE_INTERVAL = 1000 * 60 * 5;
export const POLL_VAULTS_DATA_MY_WALLET_INTERVAL = 1000 * 60 * 5;
export const POLL_VAULTS_DATA_BALANCES_INTERVAL = 1000 * 30;